/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TodoResource } from './todo-resource';

/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'todoEventType'?: EventTodoEventTypeEnum;
    /**
     * 
     * @type {TodoResource}
     * @memberof Event
     */
    'todoResource'?: TodoResource;
}

export const EventTodoEventTypeEnum = {
    TodoSave: 'TODO_SAVE',
    TodoUpdate: 'TODO_UPDATE',
    TodoDelete: 'TODO_DELETE',
    Heartbeat: 'HEARTBEAT'
} as const;

export type EventTodoEventTypeEnum = typeof EventTodoEventTypeEnum[keyof typeof EventTodoEventTypeEnum];


