/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TodoResource
 */
export interface TodoResource {
    /**
     * 
     * @type {string}
     * @memberof TodoResource
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof TodoResource
     */
    'version': number;
    /**
     * 
     * @type {string}
     * @memberof TodoResource
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof TodoResource
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof TodoResource
     */
    'status': TodoResourceStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TodoResource
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof TodoResource
     */
    'updatedAt': string;
}

export const TodoResourceStatusEnum = {
    Todo: 'TODO',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED'
} as const;

export type TodoResourceStatusEnum = typeof TodoResourceStatusEnum[keyof typeof TodoResourceStatusEnum];


