server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: '*'

app-config:
  database-name: todo-app
  database-host: localhost
  database-port: 5432

database:
  url: postgresql://${app-config.database-host}:${app-config.database-port}/${app-config.database-name}
  username: admin
  password: admin

spring:
  r2dbc:
    url: r2dbc:${database.url}
    username: ${database.username}
    password: ${database.password}
  flyway-custom:
    #    enabled: false
    url: jdbc:${database.url}
    username: ${database.username}
    password: ${database.password}

logging:
  level:
    org:
      root: INFO